### ISSUE TITLE
Generating reports

### ISSUE THREAD

**Issue by karolinak00** [karolinak00/projekt-TAB#22]
Generating report does not work (for all products and for given product):

![image](https://user-images.githubusercontent.com/56397093/177597613-1f3276fc-0783-4b12-a132-c8a6d844164e.png)
![image](https://user-images.githubusercontent.com/56397093/177597636-ea8062f4-ff38-48d8-aa33-cc01fc23f6ef.png)

**Comment by michloj571** [comment]
Done
